# Generated by Django 4.1.4 on 2023-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsosiyMahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
