# Generated by Django 4.1.4 on 2023-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarchaToifalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(max_length=20)),
                ('type3', models.CharField(max_length=20)),
                ('type4', models.CharField(max_length=20)),
                ('number1', models.ImageField(upload_to='')),
                ('number2', models.ImageField(upload_to='')),
                ('number3', models.ImageField(upload_to='')),
                ('number4', models.ImageField(upload_to='')),
            ],
        ),
    ]
