# Generated by Django 4.1.4 on 2023-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_barchatoifalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mebellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AsosiyMahsulotlar',
            new_name='MaishiyTehnikalar',
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number1',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number2',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number3',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number4',
            field=models.IntegerField(default=10),
        ),
    ]
