# Generated by Django 4.1.4 on 2023-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_maishiytehnikalarsoni_mebellarsoni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchatoifalar',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number1',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number2',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number3',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='number4',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type4',
            field=models.CharField(max_length=500),
        ),
    ]
