# Generated by Django 4.1.4 on 2023-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_barchatoifalar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchatoifalar',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barchatoifalar',
            name='type4',
            field=models.CharField(max_length=50),
        ),
    ]
