# Generated by Django 4.1.4 on 2023-01-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_barchatoifalar_name_alter_barchatoifalar_type1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maishiytehnikalar',
            options={'verbose_name': 'Maishiy Tehnika', 'verbose_name_plural': 'Maishiy Tehnika'},
        ),
    ]
