# Generated by Django 4.1.4 on 2023-01-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_barchatoifalar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barchatoifalar',
            options={'verbose_name': 'Barcha Mahsulot turlari', 'verbose_name_plural': 'Barcha Mahsulot turlari'},
        ),
    ]
